name: Pinterest Automation Bot

on:
  schedule:
    - cron: '0 */4 * * *'  # Dar 4 kalake aapod-aap run thase
  workflow_dispatch:       # Tame button dabavi ne pan run kari sako

jobs:
  run-pinterest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Pinterest Manager
        env:
          # Google Database Key
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SHEET_CONTENT_URL: ${{ secrets.SHEET_CONTENT_URL }}
          
          # Pinterest Brand Tokens (Aa badha Secrets tamara Settings ma hova joie)
          PINTEREST_TOKEN_DIAMOND: ${{ secrets.PINTEREST_TOKEN_DIAMOND }}
          PINTEREST_BOARD_DIAMOND: ${{ secrets.PINTEREST_BOARD_DIAMOND }}
          
          PINTEREST_TOKEN_PEARL: ${{ secrets.PINTEREST_TOKEN_PEARL }}
          PINTEREST_BOARD_PEARL: ${{ secrets.PINTEREST_BOARD_PEARL }}
          
          PINTEREST_TOKEN_LUXIVIBE: ${{ secrets.PINTEREST_TOKEN_LUXIVIBE }}
          PINTEREST_BOARD_LUXIVIBE: ${{ secrets.PINTEREST_BOARD_LUXIVIBE }}
          
          PINTEREST_TOKEN_URBAN: ${{ secrets.PINTEREST_TOKEN_URBAN }}
          PINTEREST_BOARD_URBAN: ${{ secrets.PINTEREST_BOARD_URBAN }}
          
          PINTEREST_TOKEN_GRAND: ${{ secrets.PINTEREST_TOKEN_GRAND }}
          PINTEREST_BOARD_GRAND: ${{ secrets.PINTEREST_BOARD_GRAND }}
          
          PINTEREST_TOKEN_ROYAL: ${{ secrets.PINTEREST_TOKEN_ROYAL }}
          PINTEREST_BOARD_ROYAL: ${{ secrets.PINTEREST_BOARD_ROYAL }}
          
          PINTEREST_TOKEN_OPUS: ${{ secrets.PINTEREST_TOKEN_OPUS }}
          PINTEREST_BOARD_OPUS: ${{ secrets.PINTEREST_BOARD_OPUS }}

        run: python pinterest_manager.py
